image: ruby:2.3

stages:
  - build
  - deploy

highlights_jekyll_theme:
  stage: build
  script:
  - gem build highlights_jekyll_theme.gemspec
  artifacts:
    paths:
    - /
    - "highlights_jekyll_theme-*.gem"
  only:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  only:
  - master